### ISSUE TITLE
Advanced Search 

### ISSUE THREAD

**Issue by marahellstern** [linked-swissbib/vufind#23]
The Advances Search currently looks like this:
![advancedsearch](https://cloud.githubusercontent.com/assets/10141833/23011003/b7735ae8-f41e-11e6-8ecc-bbc696c8c7e5.png)

**Comment by guenterh** [comment]
@marahellstern Ja, ist mir gerade auch aufgefallen. Der Fehler:

[Fri Feb 24 11:51:51.648645 2017] [:error] [pid 2983] [client 131.152.212.156:43968] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to VuFind\\View\\Helper\\Root\\SearchParams::__construct() must be an instance of VuFind\\Search\\Params\\PluginManager, instance of LinkedSwissbib\\Search\\Params\\PluginManager given, called in /usr/local/vufind/feature/module/VuFind/src/VuFind/View/Helper/Root/Factory.php on line 470 and defined in /usr/local/vufind/feature/module/VuFind/src/VuFind/View/Helper/Root/SearchParams.php:54\nStack trace:\n#0 /usr/local/vufind/feature/module/VuFind/src/VuFind/View/Helper/Root/Factory.php(470): VuFind\\View\\Helper\\Root\\SearchParams->__construct(Object(LinkedSwissbib\\Search\\Params\\PluginManager))\n#1 [internal function]: VuFind\\View\\Helper\\Root\\Factory::getSearchParams(Object(Zend\\View\\HelperPluginManager), 'searchparams', 'searchParams')\n#2 /usr/local/vufind/feature/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(939): call_user_func('VuFind\\\\View\\\\Hel...', Object(Zend\\View\\HelperPluginManager), 'searchparams', 'searchParams')\n#3 /usr/local/vufind/feature/v in /usr/local/vufind/feature/module/VuFind/src/VuFind/View/Helper/Root/SearchParams.php on line 54, referer: http://feature.swissbib.ch/Search/Results?lookfor=prima+leben&type=AllFields

schaue mir das an. Wäre jedoch froh, wenn Ihr Euch um die Sachen im Mail kümmert. G.

**Comment by marahellstern** [comment]
Current quick fix for prototype: Don't display Advanced Search: See commit https://github.com/linked-swissbib/vufind/commit/1e8816ef54c7bb35ab0091aa0a00df85bb5a5471
