### ISSUE TITLE
Exception after commit c4818c1317ffcfd8d9014cec8938ba84a67db932

### ISSUE THREAD

**Issue by ThomasWeinhold** [linked-swissbib/vufind#5]
After checking out the latest commit c4818c1317ffcfd8d9014cec8938ba84a67db932 http://localhost/sbrd/Exploration/Author?lookfor=hello is not working any more. Since the problem can be solved by going back to commit 4790b9d186c67a22394f415fe564cbbf391279b0 there must be a problem in the last commit. 

Exception:
Message: {"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[JDSYxZg6Qn6lQoVu7o6ptg][testsb][0]: SearchParseException[[testsb][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"multi_match\":{\"query\":\"hello\",\"fields\":null}}}]]]; nested: QueryParsingException[[testsb] [multi_match] query does not support [fields]]; }{[aMpceOQ1Tfe5Ihbq7DBXyg][testsb][1]: RemoteTransportException[[sb-s2][inet[/131.152.226.6:9300]][indices:data/read/search[phase/query]]]; nested: SearchParseException[[testsb][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"multi_match\":{\"query\":\"hello\",\"fields\":null}}}]]]; nested: QueryParsingException[[testsb] [multi_match] query does not support [fields]]; }{[aMpceOQ1Tfe5Ihbq7DBXyg][testsb][2]: RemoteTransportException[[sb-s2][inet[/131.152.226.6:9300]][indices:data/read/search[phase/query]]]; nested: SearchParseException[[testsb][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"multi_match\":{\"query\":\"hello\",\"fields\":null}}}]]]; nested: QueryParsingException[[testsb] [multi_match] query does not support [fields]]; }{[ZIVgCKPPRDiUHpv8DUd4fA][testsb][3]: RemoteTransportException[[sb-s7][inet[/131.152.226.73:9300]][indices:data/read/search[phase/query]]]; nested: SearchParseException[[testsb][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"multi_match\":{\"query\":\"hello\",\"fields\":null}}}]]]; nested: QueryParsingException[[testsb] [multi_match] query does not support [fields]]; }{[JDSYxZg6Qn6lQoVu7o6ptg][testsb][4]: SearchParseException[[testsb][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"multi_match\":{\"query\":\"hello\",\"fields\":null}}}]]]; nested: QueryParsingException[[testsb] [multi_match] query does not support [fields]]; }]","status":400} 

Stack/Backtrace:

```
#0 /usr/local/vufind/httpd/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(208): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /usr/local/vufind/httpd/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /usr/local/vufind/httpd/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /usr/local/vufind/httpd/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /usr/local/vufind/httpd/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(229): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#5 /usr/local/vufind/httpd/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(150): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#6 /usr/local/vufind/httpd/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(106): Elasticsearch\Connections\Connection->performRequest('GET', '/testsb/bibliog...', Array, Array, Array, Object(Elasticsearch\Transport))
#7 /usr/local/vufind/httpd/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(80): Elasticsearch\Transport->performRequest('GET', '/testsb/bibliog...', Array, Array, Array)
#8 /usr/local/vufind/httpd/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(915): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#9 /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/Connector.php(127): Elasticsearch\Client->search(Array)
#10 /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/Connector.php(64): LinkedSwissbib\Backend\Elasticsearch\Connector->send(Object(Elasticsearch\Client), Array)
#11 /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/Backend.php(108): LinkedSwissbib\Backend\Elasticsearch\Connector->search(Array)
#12 /usr/local/vufind/httpd/module/VuFindSearch/src/VuFindSearch/Service.php(107): LinkedSwissbib\Backend\Elasticsearch\Backend->search(Object(VuFindSearch\Query\Query), 0, 20, Object(LinkedSwissbib\Backend\Elasticsearch\ESParamBag))
#13 /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Search/Elasticsearch/Results.php(58): VuFindSearch\Service->search('ElasticSearch', Object(VuFindSearch\Query\Query), 0, 20, Object(LinkedSwissbib\Backend\Elasticsearch\ESParamBag))
#14 /usr/local/vufind/httpd/module/VuFind/src/VuFind/Search/Base/Results.php(234): LinkedSwissbib\Search\Elasticsearch\Results->performSearch()
#15 /usr/local/vufind/httpd/module/VuFind/src/VuFind/Controller/AbstractSearch.php(255): VuFind\Search\Base\Results->performAndProcessSearch()
#16 /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Controller/ElasticsearchController.php(36): VuFind\Controller\AbstractSearch->resultsAction()
#17 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): LinkedSwissbib\Controller\ElasticsearchController->authorAction()
#18 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#23 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#24 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#25 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#27 /usr/local/vufind/httpd/public/index.php(59): Zend\Mvc\Application->run()
#28 {main}  #0 /usr/local/vufind/httpd/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(208): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
```

**Comment by guenterh** [comment]
@ThomasWeinhold @ltog 
Hi Thomas and Lukas

sorry for this! I made a quick fix.
As you have written the error occurred because of the changes I have done but not finished so far. (Next time I'm going to use a dedicated branch...)
Now you can search without an error but more sophisticated configurations and search possibilities aren't available so far. Coming soon - hopefully!

Günter
